### ISSUE TITLE
File Location

### ISSUE THREAD

**Issue by T3chminator** [KUBIXQAZ/Scribd-downloader#1]
Where is the PDF file saved?

**Comment by KUBIXQAZ** [comment]
It is in the root folder of the application.
Output file should be named ImagesOutput.pdf.

<img width="1107" height="677" alt="Image" src="https://github.com/user-attachments/assets/117c160e-974f-41e8-b665-56156204f571" />

**Comment by T3chminator** [comment]
It is giving the following error:-

![Image](https://github.com/user-attachments/assets/8eed5b41-7f2c-412e-a2f3-95dbf3c20b8c)

**Comment by KUBIXQAZ** [comment]
I fixed the issue. Now you can download the compiled version here: https://github.com/KUBIXQAZ/Scribd-downloader/releases/tag/0.01

**Comment by T3chminator** [comment]
Thanks for the update but the issue is not fixed and is giving a different error whose screenshot I have included as follows:

![Image](https://github.com/user-attachments/assets/cf2b4112-9772-4a6f-9d28-019b9b3a9391)

The program just quit after showing that error for a couple seconds.

I wanted to ask if Chromium based browser like Edge or Chrome is required for this to work? I ask because I see reference being made to chrome driver and I have completely uninstalled Edge and only have Firefox and Brave browsers on my machine but I see Brave is a chromium based browser.

I also see that on the second last line, it is making a reference to D: drive and I do not have it as my machine just has a C drive and a Z: network drive.

**Comment by KUBIXQAZ** [comment]
I changed my approach, take a look and see if it fixes the issue. Here is the compiled version: https://github.com/KUBIXQAZ/Scribd-downloader/releases/tag/0.01 .

**Comment by T3chminator** [comment]
Works like a charm now. Much thanks :)

**Comment by KUBIXQAZ** [comment]
No problem, always happy to help
